import iphone15 from "../iphone 15 pro max.jpg";
import samsungS24 from "../sam_s24 ultra.jpg";
import pixel8 from "../Google Pixel 8 Pro.jpg";
import oneplus12 from "../OnePlus 12.jpeg";
import wirelessCharger from "../wireless charger.jpg";
import phoneStand from "../Universal Phone Stand.jpg";
import usbCharger from "../20W USB-C Fast Charger.jpg";

export const products = [
  {
    id: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    category: "phone",
    label: "Premium smartphone",
    description: "Titanium build, advanced camera system, and top-tier performance.",
    price: 134900,
    badge: "New",
    image: iphone15,
    imageFit: "contain",
    imageSize: "92%",
    background: "linear-gradient(180deg, #13151d 0%, #090a0e 100%)",
    features: ["6.7-inch Super Retina display", "Pro camera system", "All-day battery life"],
  },
  {
    id: "samsung-s24-ultra",
    name: "Samsung S24 Ultra",
    category: "phone",
    label: "Flagship smartphone",
    description: "A powerful Android flagship with a sharp display and pro-grade camera tools.",
    price: 129999,
    badge: "Popular",
    image: samsungS24,
    imageFit: "contain",
    imageSize: "92%",
    background: "linear-gradient(180deg, #12131a 0%, #08090c 100%)",
    features: ["Dynamic AMOLED display", "S Pen support", "High-resolution zoom camera"],
  },
  {
    id: "google-pixel-8-pro",
    name: "Google Pixel 8 Pro",
    category: "phone",
    label: "Smartphone",
    description: "Clean Android experience with excellent photography and smart AI features.",
    price: 106999,
    image: pixel8,
    imageFit: "contain",
    imageSize: "92%",
    background: "linear-gradient(180deg, #10121a 0%, #07080d 100%)",
    features: ["Pure Android", "Tensor-powered AI tools", "Best-in-class camera tuning"],
  },
  {
    id: "oneplus-12",
    name: "OnePlus 12",
    category: "phone",
    label: "Performance phone",
    description: "Fast, fluid, and built for users who want speed without compromise.",
    price: 949,
    badge: "Fast",
    image: oneplus12,
    imageFit: "contain",
    imageSize: "88%",
    background: "linear-gradient(180deg, #101611 0%, #07090a 100%)",
    features: ["120 Hz LTPO display", "SuperVOOC fast charging", "Performance-first chipset"],
  },
  {
    id: "wireless-charger",
    name: "Wireless Charger",
    category: "accessory",
    label: "Charging accessory",
    description: "Clean desk charging with a low-profile pad and dependable output.",
    price: 39,
    badge: "Accessory",
    image: wirelessCharger,
    imageFit: "contain",
    imageSize: "94%",
    background: "linear-gradient(180deg, #101114 0%, #07080a 100%)",
    features: ["Wireless fast charging", "Compact desk-friendly design", "Thermal protection"],
  },
  {
    id: "phone-stand",
    name: "Universal Phone Stand",
    category: "accessory",
    label: "Stand accessory",
    description: "A sturdy adjustable stand for calls, media, and hands-free work.",
    price: 24,
    badge: "Accessory",
    image: phoneStand,
    imageFit: "cover",
    imageSize: "100%",
    background: "linear-gradient(180deg, #11131a 0%, #08090c 100%)",
    features: ["Adjustable viewing angle", "Works with most phones", "Solid non-slip base"],
  },
  {
    id: "usb-c-fast-charger",
    name: "20W USB-C Fast Charger",
    category: "accessory",
    label: "Charging accessory",
    description: "A compact wall charger for quick everyday top-ups.",
    price: 19,
    badge: "Accessory",
    image: usbCharger,
    imageFit: "contain",
    imageSize: "90%",
    background: "linear-gradient(180deg, #101115 0%, #07080b 100%)",
    features: ["20W power delivery", "USB-C output", "Travel-friendly size"],
  },
];
